### ISSUE TITLE
Unit tests occasionally fail in CI

### ISSUE THREAD

**Issue by kitsuyui** [kitsuyui/rendering-proxy#262]
It will succeed after several retries.
Perhaps it takes a long time for the browser to start up, and it is not in time.
Fix the test.

example: https://github.com/kitsuyui/rendering-proxy/runs/7779845291

```

    thrown: "Exceeded timeout of 5000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      4 |
      5 | describe('renderToStream', () => {
    > 6 |   it('render', async () => {
        |   ^
      7 |     const texts: string[] = [];
      8 |     const writable = new Writable({
      9 |       write(chunk, encoding, callback) {

      at it (src/cli/index.spec.ts:6:3)
      at Object.describe (src/cli/index.spec.ts:5:1)
```

Unit tests may fail in other places than this example.

**Comment by kitsuyui** [comment]
Close by #294
